Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py'}
                                                                   
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
>>> a
10
>>> a*a
100
>>> a
10
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py'}
                                                                   
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
>>> a
10
>>> vars()
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
>>> print(__builtins__ .__doc__ )
Built-in functions, exceptions, and other objects.

Noteworthy: None is the `nil' object; Ellipsis represents `...' in slices.
>>> __builtins__.TypeError
<class 'TypeError'>
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py'}
                                                                   
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 7, in <module>
    printf(coas(a))
NameError: name 'printf' is not defined
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py'}
                                                                   
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 7, in <module>
    print(cos(a))
NameError: name 'cos' is not defined
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py'}
                                                                   
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
-0.8390715290764524
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py'}
                                                                   
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 8, in <module>
    print(cos(a))
NameError: name 'cos' is not defined
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py'}
                                                                   
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10}
-0.8390715290764524
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
-0.8390715290764524
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
-0.8390715290764524
-0.8390715290764524
>>> vars()
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/RTR108/nodarb_0/python_tests.py', 'a': 10, 'math': <module 'math' (built-in)>, 'cos': <built-in function cos>, 'cos_v1': <built-in function cos>}
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
-0.8390715290764524
-0.8390715290764524
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 17, in <module>
    print(cos_v2(a))
NameError: name 'cos_v2' is not defined
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
-0.8390715290764524
-0.8390715290764524
-0.8390715290764524
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
-0.8390715290764524
-0.8390715290764524
(-0.8390715290764524+0j)
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 10, in <module>
    import cos as math_v1
ModuleNotFoundError: No module named 'cos'
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 10, in <module>
    import cos as math_v1
ModuleNotFoundError: No module named 'cos'

============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 11, in <module>
    print(math.cos_v1(a))
AttributeError: module 'math' has no attribute 'cos_v1'
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
Traceback (most recent call last):
  File "/home/user/RTR108/nodarb_0/python_tests.py", line 11, in <module>
    print(math_v1.cos_v1(a))
AttributeError: module 'math' has no attribute 'cos_v1'
>>> 
============ RESTART: /home/user/RTR108/nodarb_0/python_tests.py ============
-0.8390715290764524
-0.8390715290764524
-0.8390715290764524
-0.8390715290764524
(-0.8390715290764524+0j)
-0.8390715290764524
>>> 
